apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jha1l1w1v-dotnet-basic
  janus-idp.io/tekton: jha1l1w1v-dotnet-basic
  backstage.io/kubernetes-id: jha1l1w1v-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jha1l1w1v-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
